// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGNb2LoFZZAVI2UJh3MMkMJMJeC5zgZ-I',
    appId: '1:297588837297:web:68d3dd0ae6828a7066cb90',
    messagingSenderId: '297588837297',
    projectId: 'gestion-taches-17969',
    authDomain: 'gestion-taches-17969.firebaseapp.com',
    storageBucket: 'gestion-taches-17969.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2i8cmB7b0D4oK9PI_3u84_k7F8kUjuWY',
    appId: '1:297588837297:android:7d0342d5bb997f3066cb90',
    messagingSenderId: '297588837297',
    projectId: 'gestion-taches-17969',
    storageBucket: 'gestion-taches-17969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAFQtylVjA8CVDFCu1-SOQufq97eavKc',
    appId: '1:297588837297:ios:c1c82c559fddff6e66cb90',
    messagingSenderId: '297588837297',
    projectId: 'gestion-taches-17969',
    storageBucket: 'gestion-taches-17969.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIAFQtylVjA8CVDFCu1-SOQufq97eavKc',
    appId: '1:297588837297:ios:b6a6bc0ad8bad89066cb90',
    messagingSenderId: '297588837297',
    projectId: 'gestion-taches-17969',
    storageBucket: 'gestion-taches-17969.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
